### ISSUE TITLE
Increasing the HDFS.log data size to more number is causing the model to fail? Could you please help? IF we change the data size, should we alter anything?

### ISSUE THREAD

**Issue by revraj1207** [YintongHuo/SemParser#4]
We have 6580 data in total in V1
Traceback (most recent call last):
  File "/home/ubuntu/SemParser-main/model/main.py", line 322, in <module>
    test_model(model, word_emb_dir, test_dir, finetuneset='HDFS_50K')
  File "/home/ubuntu/SemParser-main/model/main.py", line 247, in test_model
    outputs = test(data, model)
  File "/home/ubuntu/SemParser-main/model/main.py", line 142, in test
    predicts, predict_token_label = model.predict(batch_word, batch_wordlen, batch_char, batch_charlen, batch_charrecover, batch_combine, batch_combine_labels, word_features)
  File "/home/ubuntu/SemParser-main/model/model/corefmodel.py", line 168, in predict
    predict_token_label = torch.argmax(self.token_type_classifier(mention_feat).squeeze(), dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Fushaochen** [comment]
replace torch.argmax(self.token_type_classifier(mention_feat), dim=1)
